routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('browns');
});

Route::resource("subscribers", "SubscribersController");

app/Subscriber.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subscriber extends Model
{
    protected $table = 'subscribers';
    protected $fillable = ['email','subscribed'];
    public $timestamps = true;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SubscribersController.php
<?php

namespace App\Http\Controllers;

use App\Subscriber;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\DB;

class SubscribersController extends Controller
{
    protected $subscriber;
    //build the subscription form
    public function index(){
        //load a view directly
        return view('subscribe-form');
    }

    public function store(Request $request){

        //validate $request
        $request->validate([]);
        $subscriber = new Subscriber();
        $subscriber->email = $request->input('email');
        $subscriber->subscribed = $request->input('doi');
        $this->subscriber = $subscriber;
    }
}

resources/views/errors.blade.php
<!-- quick way to show user errors, via laravel docs -->
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield("title","Title")</title>
    @include('mainstyle')
</head>
<body>

<div class="content container">
    <div class="title">
        @yield("header")
    </div>
    <div class="row">
        @yield("content")
    </div>
</div>
@include('mainscripts')
</body>
</html>

resources/views/mainscripts.blade.php
<!-- Compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="/js/app.js" type="text/javascript"></script>
@yield("pagescripts")

resources/views/mainstyle.blade.php
<!--Import Google Icon Font-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Materialize-->
<link type="text/css" href="/css/app.css" rel="stylesheet"/>
@yield("pagestyle")

resources/views/privacy.blade.php
@extends("layout");
@section("title","Our Privacy Policy Promise")
@section("header","Our Privacy Policy Promise")
@section("content")
    <h3>Our Privacy Promise</h3>
    <ul>
        <li>We collect, use and store your personal data so that we can offer you the best products, services and website experience possible.</li>
        <li>Your personal data is exactly what it says, it is yours and as such we are respectful of how we use it and how long we keep it.</li>
        <li>We will always be transparent with you about what we do with your personal data, and we will always ensure that it is secure.</li>
        <li>When we share your data with our service providers, we will always make sure they match our high levels of security.</li>
        <li>From time to time you will receive marketing communications from us which keep you up to date with all our latest products, services and offers. We believe this is a legitimate part of the Joe Browns customer experience.</li>
        <li>We will always offer you a clear and simple means of changing your communication preferences whenever you want to.</li>
    </ul>
@endsection

resources/views/subscribe-form.blade.php
@section("title","Confirm Newsletter Subscription")
@section("header","Subscribe to our newsletter for 10% off!")
<!-- sticky floating notification -->
<div class="fixed-mail-btn hide-on-small-only">
    <div class="fixed-notification-badge red center-align z-depth-1">1</div>
    <a class="waves-effect waves-light modal-trigger" href="#modal1"><i class="large material-icons mail-floating">mail</i></a>
</div>
<!-- sign up form -->
<div class="row pin-form">
    <a class="waves-effect waves-light modal-trigger" href="#modal1" >
    <div id="newsletter-signup" class="col s12 offset-s1 offset-m2">
        <div class="row d-block" style="margin-bottom: 0;padding-top: 0.2rem">
            <div class="col s8 padding-off">
                <input id="newsletter-email" class="input-field sub-field" type="email" name="subscriber-email"
                       placeholder="Enter email for 10% off your first order">
            </div>
            <div class="col s4 padding-off">
                <button class="btn-sub waves-effect waves-light z-depth-0 modal-trigger"  data-target="modal1" name="signup"
                        value="Sign Up">Sign Up<i class="material-icons right hide-on-small-only">send</i>
                </button>
            </div>
        </div>
    </div>
    </a>
</div>

<!-- Modal Structure -->
<div id="modal1" class="modal">
    <div class="modal-header">
        <img src="https://1039206484.rsc.cdn77.org/assets/images/jb-logo-@2x.png" class="img-fluid mx-auto" alt="Joe Browns logo">
    </div>
    <div class="mmodal-content">
        <h4>Subscribe now for 10% off your first order</h4>
        @include("errors")
        <form id="newsletter-signup" class="col s12 offset-s1 offset-m2" method="POST" action="{{route('subscribers.store')}}">
            @csrf
            <div id="doi" class="row center-align">
                <div class="col s12">
                    <label for="newsletter-doi-check">Yes, I want to subscribe!
                        <input id="newsletter-doi-check" name="newsletter-doi-check" type="checkbox" class="filled-in" required><span style="color: rgb(164, 50, 38)">*</span>
                    </label>
                </div>
            </div>
            <div class="row d-block">
                <div class="col s8 offset-s1 padding-off">
                    <input id="newsletter-email" onchange="this.setCustomValidity(validity.valueMissing ? 'Enter a valid email address': '');" class="input-field sub-field validate" required type="email" name="subscriber-email"
                           placeholder="Enter email for 10% off your first order">
                </div>
                <div class="col s3 padding-off">
                    <button class="btn-sub waves-effect waves-light z-depth-0 flow-text" type="submit" name="signup"
                            value="Sign Up">Sign Up<i class="material-icons right hide-on-small-only">send</i>
                    </button>
                </div>
            </div>
            <div class="row d-block">
                <div class="col s12 offset-s1 padding-off">
                    <span class="helper-text" data-error="Please enter a valid email" data-success=""/>
                </div>
            </div>

            <div id="tacs" class="row d-block">
                <span class="col s10 offset-s1 padding-off">By clicking 'Sign Up' you will be subscribed to our mailing list and accept our
                <a href="https://www.joebrowns.co.uk/pu+terms-and-conditions+terms+1" target="_blank">terms and conditions</a> and
                <a href="https://www.joebrowns.co.uk/pu+privacy+privacy+1" target="_blank">privacy policy.</a>
                </span>
            </div>
        </form>
    </div>
    <div class="mmodal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a>
    </div>
</div>

resources/views/terms-conditions.blade.php
@extends("layout");
@section("title","Email Newsletter Policy")
@section("header","Email Newsletter Policy")
@section("content")
    <ul>
        <li>Win £100 Email Newsletter Competition</li>
        <li>One winner will be selected from new email newsletter signups each calendar month.</li>
        <li>The prize awarded will be £100 in Joe Browns vouchers to be used at joebrowns.co.uk or via telephone (0113 270 6655).</li>
        <li>Prize cannot be exchanged for monetary equivalent.</li>
        <li>Winners will be contacted within two working days of draws being made.</li>
        <li>This competition is not open to employees of Joe Browns or family members of employees.</li>
        <li>Our decision is final.</li>
    </ul>
@endsection